CREATE TABLE USERS (
	_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    email VARCHAR(70) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    verified BOOLEAN DEFAULT FALSE,
    verificationToken VARCHAR(255),
    modifiedAt TIMESTAMP DEFAULT NULL,
    createdAd TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)